
name: build

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            args: gnu x86_64

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            args: gnu aarch64

          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            args: musl x86_64

          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
            args: musl aarch64

          - target: x86_64-apple-darwin
            os: macos-latest
            args: x86_64

          - target: aarch64-apple-darwin
            os: macos-latest
            args: arm64

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            args: x64

          - target: aarch64-pc-windows-msvc
            os: windows-latest
            args: arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install LLVM (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Build (macOS)
      if: startsWith(matrix.os, 'macos')
      run: python3 ./build.py ${{ matrix.args }}

    - name: Build (Windows)
      if: startsWith(matrix.os, 'windows')
      shell: cmd 
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -find Common7\Tools\VsDevCmd.bat`) do (
          call "%%i"
        )
        python3 ./build.py ${{ matrix.args }}

    - name: Build (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: sh build_linux.sh ${{ matrix.args }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: out

  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    needs: [build]
    steps:
    - uses: actions/download-artifact@v4
      with: 
        name: x86_64-unknown-linux-gnu
        path: x86_64-unknown-linux-gnu

    - uses: actions/download-artifact@v4
      with: 
        name: aarch64-unknown-linux-gnu
        path: aarch64-unknown-linux-gnu

    - uses: actions/download-artifact@v4
      with: 
        name: x86_64-unknown-linux-musl
        path: x86_64-unknown-linux-musl

    - uses: actions/download-artifact@v4
      with: 
        name: aarch64-unknown-linux-musl
        path: aarch64-unknown-linux-musl

    - uses: actions/download-artifact@v4
      with: 
        name: x86_64-apple-darwin
        path: x86_64-apple-darwin

    - uses: actions/download-artifact@v4
      with: 
        name: aarch64-apple-darwin
        path: aarch64-apple-darwin

    - uses: actions/download-artifact@v4
      with: 
        name: x86_64-pc-windows-msvc
        path: x86_64-pc-windows-msvc

    - uses: actions/download-artifact@v4
      with: 
        name: aarch64-pc-windows-msvc
        path: aarch64-pc-windows-msvc

    - name: make artifacts
      run: |
        mkdir artifacts
        cp x86_64-unknown-linux-gnu/out artifacts/x86_64-unknown-linux-gnu
        cp aarch64-unknown-linux-gnu/out artifacts/aarch64-unknown-linux-gnu
        cp x86_64-unknown-linux-musl/out artifacts/x86_64-unknown-linux-musl
        cp aarch64-unknown-linux-musl/out artifacts/aarch64-unknown-linux-musl
        cp x86_64-apple-darwin/out artifacts/x86_64-apple-darwin
        cp aarch64-apple-darwin/out artifacts/aarch64-apple-darwin
        cp x86_64-pc-windows-msvc/out artifacts/x86_64-pc-windows-msvc
        cp aarch64-pc-windows-msvc/out artifacts/aarch64-pc-windows-msvc

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
        name: Continuous build
        allowUpdates: true
        tag: latest_build
        commit: ${{ github.ref }}
        makeLatest: true
